
const fs = require('fs');
const path = require('path');

// Read the script file
const scriptPath = path.join(__dirname, 'script.js');
let scriptContent = fs.readFileSync(scriptPath, 'utf8');

// Extract the studentsData object using regex or valid parsing (since it's a JS file, we can't just require it easily without module.exports)
// However, looking at the file, it's a simple const variable.
// I'll copy the object structure manually here for safety to ensure I get it right, 
// or I can just eval the specific part if I'm careful. 
// Safest is to just paste the data here since I have it from the view_file.

const studentsData = {
    cs1: {
        "1": "ABDUL MUTHAYEEB", "2": "ADIMULAM SHREYANK", "3": "AKULA VAMSHI KRISHNA",
        "4": "ANALA MANIKANTA", "5": "APARADI AKSHAYA", "6": "B AKHIL CHANDRAMOULI",
        "7": "B R M ADITYA", "8": "BANDHANADHAM YESHWANTH KUMAR",
        "9": "BANTU ASHOK", "10": "BATHULA SIDHARTHA", "11": "BATHULA VIKAS",
        "12": "BAVANDLAPELLI SRIRAM", "13": "BEJJANKI MANIDEEP REDDY",
        "14": "BHOORAM VARSHINI", "15": "BHUKYA ARAVIND",
        "16": "BODEGE DIPIN KUMAR GOUD", "17": "BOLLIKONDA ABHINAV",
        "19": "BURALA LEELA ANANTH", "20": "CHIKOTI BALA SAKSHITHA",
        "21": "CHILARAPU VARUN KUMAR", "22": "CHILUMULA RAHUL",
        "23": "CHINTHAKINDI SAMPATH", "24": "CHIPPA ROHITH",
        "25": "DAMERA HARSHAVARDHAN", "26": "DASOJU GANESH",
        "27": "DAYYALA RAJINI", "28": "DEVALLA DILIP CHANDU",
        "29": "DEVIKA VIJAY KUMAR COUGNERY", "30": "DHARAVATH NITHIN",
        "31": "SHANMUKHARAJYAPRANEETH", "32": "DIDLA SAI SANTHOSHINI",
        "33": "ERJALA MANOJ", "34": "GANAMONI KEERTHI",
        "35": "GANGANABOINA KOMALI", "36": "GOLLA SHIVA PRASAD",
        "37": "GOPIDI NACHIKETH", "38": "GOSHA ANURAAG",
        "39": "GOTTAM NIHARIKA", "40": "GUMMAKONDA MANOJ REDDY",
        "41": "GUNDAMALLA VINAY KUMAR", "42": "HARIJAN PANDU",
        "43": "INDIRALA VINAY", "44": "JAKKULA KARTHIK",
        "45": "JAMPAANA RAHUL", "46": "JANGAM RAGHAVA",
        "47": "K KARTHIK REDDY", "48": "KADARI SHARMILA",
        "49": "KAMPALLI ARAVIND", "50": "KANCHARLA KRISHNA SASIDHAR",
        "51": "KARNAKOTI VISHAL", "52": "KATRAPALLI SAI VIGNYATHRI",
        "53": "KAVURI SRI SAI SHARANYA", "54": "KODANGAL MANIDEEPIKA",
        "55": "KODOLLA SANTOSH", "56": "KODUKULA SAI SRIKAR",
        "57": "KOLLA VINEETH", "58": "KOMIRA VYSHALI",
        "59": "KOMMULA SHIVANI", "60": "KONDOJU ABHINAV",
        "61": "K THIRUMALESHWAR", "62": "KORRA ANJALI",
        "63": "KRISHITA PAWAR", "64": "KUNAMALLA ASMITHA",
        "65": "KUNCHA RAHUL",
        "LE1": "ABUSI SATHWIKA", "LE2": "ALAVALA SAMATHA",
        "LE3": "BOIDI MANASA", "LE4": "CHENABOINA SURYA TEJA",
        "LE5": "DODLE KRISHNA", "LE6": "MANGALAPALLY SHIVA"
    },
    cs2: {
        "66": "KUNCHALA ANURADHA", "67": "KUNCHAM CHANDU", "68": "KUNDEY VENU", "69": "M ATHIKA NAYEEM", "70": "MALOTH PRAVALIKA", "71": "MAMIDI KUSHI", "72": "MAMIDI SHREYAS ", "73": "MANDALA SHESHIKANTH REDDY", "74": "MANGALAGIRI SWETHA SRI", "75": "MANMARI BHARATH KUMAR", "76": "MANYAM CHARAN SATEESH", "77": "MARADANA HIMATEJ", "78": "MARTHA ABHINESH", "79": "MD RAMEEZ RAJA", "80": "MEDI MANU SRI", "81": "MEGHAVATH CHIRANJEEVI",
        "82": "MENDU MAHITHA", "83": "METLA NAVEEN KUMAR",
        "84": "MOHAMMAD ASIF QUARAN", "85": "MUDAVATH BHAVITHA", "86": "MUDIGONDA KARTHIK", "87": "MULA SRIVANI", "88": "O. SANKEERTHANA", "89": "P CHAITHRIKA", "90": "PADMA LAXMI NARAYANA",
        "91": "MAHESH BABU PALAPARTHI", "92": "PATEL JAGADEESH",
        "93": "PATHAKOTI VEDHAVYAS", "94": "PENTAM VAISHNAVI", "95": "PERUMALLA ANURAG VARSHITH", "96": "PODETI ADITHYA", "97": "PULAVAR VISHWAKANTH", "98": "PUNNA VAISHNAVI",
        "99": "PUPPALA SRI VAISHNAVI CHARITHA", "A0": "PURRE TANISHA VALARIE", "A1": "R SUVIDHA", "A2": "RAJAMONI MAMATHA", "A3": "RAMAVATH LAXMAN", "A4": "RAPARTHI HANSIKA GOUD", "A5": "RASALA KALYAN", "A6": "RISHI SELOTE", "A7": "S SAI RAKSHITH REDDY", "A8": "SABAVATH ESHWAR ", "A9": "SAGGERLA THEJESWAR",
        "B0": "SANGI PAVAN KUMAR", "B1": "SATHVIK RAVI", "B2": "SHAIK ARIF", "B3": "SHAIK ASLAM", "B4": "SHAIK IMRAN", "B5": "SHAIK SAMAD",
        "B6": "SINGANABOINA ADARSH", "B7": "SONTE KARTHIK", "B8": "SUMREDDY HRITHIK REDDY", "B9": "SURKANTI SHREYAS MAHENDRA REDDY",
        "C0": "T G VENKATESH", "C1": "THELLA SAI PARTHA ", "C2": "THONDAPU SASHIDHAR", "C3": "TUNGA SHRAVAN", "C4": "UDAVATH NEHRU NAIK", "C5": "V TEJASWINI", "C6": "VARIKUPPALA HINDU",
        "C7": "VIVEK CHOURASIA", "C8": "VUPPARABOINA SRUJAN KUMAR", "C9": "YASARAPU SRIHITHA", "le7": "MOULA RAGHAVENDAR",
        "Le8": "NARA ABHINAY", "le9": "PASHIKANTI NEERAJ", "le10": "PASTHAM KARTHIK", "le11": "PENDYALA SHIVA KARTHIK", "le12": "SYED MUDASEER SADAF", "le13": "VEERANKI SANTHOSH TEJA"

    },
    ds1: {
        "1": "ABHIRUP KUMAR", "2": "ADIPUDI NAINIKA",
        "3": "AILURI UPENDER REDDY",
        "4": "AKULA POOJITHA", "5": "AKUTHOTA BINDHU", "6": "AMULYA DEV", "7": "ANAGALA MAHESH", "8": "ASURI SANKEERTH", "9": "AVULA VAMSHIDHAR", "10": "B RAVI SHANKAR NAIDU",
        "11": "BADINI LOKESH", "12": "BALAGONI SNEHA", "13": "BALGURI MANI CHANDU",
        "14": "BANALA PAVAN KUMAR",
        "15": "BANDARI VINAY", "16": "BANOTH VISHAL", "17": "BAYYA AJAY", "18": "BHUSI NOHITHA", "19": "BOGA VISHWANATH", "20": "BOJJA SINDHU", "21": "BURADA CHARAN TEJA",
        "22": "BUSHE BHANU PRASAD",
        "23": "CHEVVALA DIVYA", "24": "CILAMKOTI NIHAL", "25": "DAKKUMALLA GIDEON RAJ",
        "26": "DANDU DEEKSHITHA", "27": "DASARI MITHRA", "28": "DHANAVATH BINDHU", "29": "DIDYALA MANISH KUMAR",
        "30": "DODDIMIDI RAHUL", "31": "DUMANI MADHUR", "32": "ERPULA RAMESH", "33": "GADALA VENKATA RAJENESH",
        "34": "GADDAM SUPRITH REDDY",
        "35": "GANTA AJAY", "36": "GOLLA ANVESH", "37": "GORRE KARTHIKEYA", "38": "GOUDAPOLLA BHAVANA",
        "39": "GOUNDLA SREEJA", "40": "GUDISE HARSHITHA", "41": "GUNDA SAI KUMAR", "42": "HARLEEN KAUR SENA", "43": "J SHIVA KUMAR", "44": "JAHAGIRDAR MAYURESH",
        "45": "JAMMULA VINEEL KUMAR",
        "46": "JASVINDER KAUR", "47": "JATANGI LOKESH", "48": "JIDUGU AJAY KUMAR", "49": "KADARI SWAPNA", "50": "KAIRAMKONDA JASHWANTH", "51": "KAMMADANAM SHARANYA", "52": "KANUMALLA AKHIL", "53": "KASHISH MANGLANI", "54": "KASOJU SOWJANYA", "55": "KEERTHI SAI VAMSHI", "56": "KELOTH SAI CHARAN", "57": "KETHAVATH MADHAVI", "58": "KETHIREDDY BABA VAIBHAV ",
        "59": "KOSIREDDY VINEEL", "60": "KOTHA AKSHAYA", "61": "KOULOJU JAYESH", "62": "KUMBHAM SHAIINIT VARSHA",
        "63": "KURMETI MANUSHA", "64": "MACHA KARTHIK", "65": "MADASU SRIVIDHYA", "le1": "ADEPOJU SRI CHANDANA",
        "le2": "APPANA VYSHNAVI", "le3": "AVULA MAHESHWAR", "le4": "BOORA ROHITH", "le5": "BUDUGULA DIVYA", "le6": "CHILUKA YESHWITH"
    },
    ds2: {

        "66": "MADUGULA TEJASWINI",
        "67": "PULLURI SHLOKA", "68": "MANNEPU MANOJ KUMAR REDDY", "69": "MANUMALA JASWANTH",
        "70": "MANYAM NITHISH", "71": "MD SANA",
        "72": "MD SHABBIR PASHA", "73": "MEKALA THARUNI", "74": "MOHAMMAD DASTHAGIR", "75": "MOHAMMED AYAAN", "76": "MUDAVATH YADESHWARI", "77": "MULPUR RUTHWIK KUMAR",
        "78": "MUNESH SINGH", "79": "NAKKA GIRISHA", "80": "NAKKALA RISHITHA", "81": "NAVATH RAGHAVENDRA", "82": "NAVLURI NEHASRI", "83": "NYARAMONI VAISHNAVI", "84": "PADAKANTI ANKITHA", "85": "PADALA SAI CHARAN", "86": "PADIGELA ANUP REDDY",
        "88": "PANDRAVETI BHANU THEJA",
        "89": "PANGA NARESH", "90": "PIDISHETTY NEHA", "91": "PINIREDDY SAHARSH REDDY",
        "92": "POLOJU NAVADEEP", "93": "RAJALA MADHULATHA", "94": "RAMAVATH DEVENDAR", "95": "RAMAVATH JEEVAN KUMAR",
        "96": "RAMPALLI RAHUL", "97": "REDDY ROHITH REDDY",
        "98": "REKULAPALLY SRAVYA",
        "99": "RUPAVATH MADHAVI", "A0": "S ANKITH", "A1": "SABAVATH ARAVIND", "A2": "SADAM NAINITHA", "A3": "SAIKRISHNA PENDEM", "A4": "SALENDRA RAJ KUMAR",
        "A5": "S. CHANDRAKANTH", "A6": "SAVANAPALLY SRICHARAN", "A7": "SETTIPALLI MAHIKA", "A8": "SHERI THANUSH KUMAR",
        "A9": "SULAM ROHITH", "B0": "SURUKUNTI SHASHANK",
        "B1": "T ARCHANA", "B2": "TAMBALA SANGHAVI", "B3": "THADURI AKHIL", "B4": "THIKKALA NAVYASREE", "B5": "THIRUMALESH KANDOOR",
        "B6": "TUMMA HAINDAVI", "B7": "VALLEPU GOUTHAM", "B8": "VALLURI ROHAN", "B9": "VANAM AKASH", "C0": "VANAM SAMPATH", "C1": "VASPARI MANASA", "C3": "VEYIGANDLA MADHULITHA", "C4": "VISLAVATH ROHIT RAJ",
        "C5": "VORAGANTI LAXMINARASIMHA", "C6": "YAMALA MANASA", "C7": "YEKKITEELA HARSHITH SAI",
        "C8": "YENGLA LALITHA SRI", "le7": "DEEPANKER",
        "le8": "E SHIVA NAND", "le9": "GOKA ABHILASH REDDY",
        "le10": "GUNDREDDY HARIKA",
        "le11": "NALLAGANTI ESHWAR",
        "le12": "SAMUDRALA SAI TEJA",
        "le13": "TELAKALAPELLI RAKESH", "le14": "VANNELADAS KARTHIK"
    }
};

const SECRET_KEY = "mySuperSecretKeyForStudents";

function encrypt(text) {
    const textBytes = Buffer.from(text, 'utf8');
    const keyBytes = Buffer.from(SECRET_KEY, 'utf8');
    const result = Buffer.alloc(textBytes.length);
    for (let i = 0; i < textBytes.length; i++) {
        result[i] = textBytes[i] ^ keyBytes[i % keyBytes.length];
    }
    return result.toString('base64');
}



// fs is already required at the top
const jsonStr = JSON.stringify(studentsData);

// function encrypt and SECRET_KEY are already defined above

const encrypted = encrypt(jsonStr);

fs.writeFileSync('encrypted_data.txt', encrypted);
console.log("Encryption complete. Data written to encrypted_data.txt");
